INSERT OR REPLACE INTO prompts (id, title, market, tag, prompt_text, is_free, created_at, updated_at) VALUES
('trend-20260801-action-figure','2026 Collectible Action Figure Box','Global','Trending','Turn the person in my uploaded photo into a generic collectible action figure sealed inside clear blister packaging. Preserve the face, hairstyle, body shape, outfit colors, and recognizable accessories. Use glossy molded plastic texture, premium studio lighting, a clean retail product-photo background, and 2-3 hobby accessories beside the figure. Add no real brand names, no logos, no celebrity references, and no readable text. Square 1:1 composition for Instagram.',1,datetime('now'),datetime('now')),
('trend-20260801-polaroid','AI Polaroid Memory Frame','Global','Trending','Transform this photo into a vintage instant-film snapshot from the late 1990s. Keep the subject recognizable, add a thick white instant-photo border with extra space at the bottom, hard on-camera flash, warm faded colors, fine film grain, slight softness, edge falloff, and a candid unposed memory feeling. Do not include celebrities or people without consent. 4:5 Instagram crop.',1,datetime('now'),datetime('now')),
('trend-20260801-y2k-camcorder','Y2K Camcorder Flash Edit','Global','Trending','Edit my photo like a chaotic early-2000s camcorder still. Preserve my face and main outfit, add direct flash overexposure, cool indoor lighting, low-resolution VHS texture, subtle scanlines, small timestamp-style graphic shapes without readable text, slight motion blur, and a casual party snapshot mood. Use vertical 9:16 composition for TikTok, Reels, or Stories.',1,datetime('now'),datetime('now')),
('trend-20260801-scrapbook','Scrapbook Digital Journal Collage','Global','Trending','Turn this photo into a handmade scrapbook journal collage. Keep the person recognizable, layer torn notebook paper, tape pieces, soft stickers, pressed flowers, faded magazine cutouts, doodle-like shapes, coffee-stain texture, and pastel color grading around the image. Make it feel tactile and personal, not polished AI. No readable fake handwriting or brand logos. 4:5 Instagram feed composition.',1,datetime('now'),datetime('now')),
('trend-20260801-movie-poster','Text-Free Indie Movie Poster','Global','Trending','Create a dramatic indie movie-poster style image from this portrait while preserving identity. Use cinematic shadows, subtle film grain, moody editorial color grading, atmospheric background depth, elegant negative space, and a powerful main-character expression. Do not add title text, actor names, critic quotes, studio logos, or copyrighted movie references. 2:3 poster composition.',1,datetime('now'),datetime('now')),
('trend-20260801-time-travel','1980s Neon Time Travel Portrait','Global','Trending','Place the person from my photo into a rainy 1980s neon city street at night. Preserve the face and natural proportions, adapt the outfit into era-appropriate retro streetwear, add glowing shop signs without readable text, wet pavement reflections, cinematic fog, realistic shadows, film-grain texture, and teal-magenta color grading. Use 4:5 vertical Instagram composition.',1,datetime('now'),datetime('now')),
('trend-20260801-mirror-selfie','Warm LED Mirror Selfie Prompt','South Asia / Global','Trending','Use my uploaded photo as a strict identity reference and create a realistic mirror selfie in a clean modern room. Preserve my face, hairstyle, skin tone, and body proportions. Add a warm LED arch mirror glow, stylish but believable outfit, phone-camera realism, natural skin texture, slight background blur, soft indoor shadows, and a casual confident pose. No brand logos, no fake text, 3:4 portrait crop.',1,datetime('now'),datetime('now')),
('trend-20260801-monsoon','Cinematic Monsoon Rain Portrait','South Asia / Global','Trending','Transform this photo into a cinematic monsoon rain portrait. Preserve every visible person’s identity, add umbrellas or rain-soaked street atmosphere only if it fits the pose, warm street lights, wet pavement reflections, soft rim light, natural skin texture, realistic fabric detail, cozy emotional mood, and subtle film grain. Avoid fake logos or readable text. 4:5 Instagram composition.',1,datetime('now'),datetime('now'));
