export const site = {
  name: 'PromptSeen Online',
  domain: 'https://promptseen.online',
  contactEmail: 'zjjhgtw@gmail.com',
  description:
    'Find Prompt Seen style AI photo prompts for Gemini, ChatGPT and Instagram. Copy cricket, Bollywood, Eid, Ramadan and South Asian creator ideas.',
  clarityId: 'x0vmlezgsz',
  gaId: 'G-HJ16WBEHPL',
  gscVerification: '',
} as const;

export const mainRoutes = [
  { href: '/', label: 'Home' },
  { href: '/prompts', label: 'Prompts' },
  { href: '/categories', label: 'Categories' },
  { href: '/pricing', label: 'Pricing' },
  { href: '/generate', label: 'Generate' },
  { href: '/account', label: 'Account' },
] as const;

export type Prompt = {
  title: string;
  market: string;
  tag: string;
  tool: 'Gemini' | 'ChatGPT' | 'Dreamina' | 'Any AI image tool';
  useCase: string;
  prompt: string;
  image: string;
  imageAlt: string;
};

export const prompts: Prompt[] = [
  {
    title: 'Prompt Seen Cricket Stadium DP',
    market: 'India / Pakistan',
    tag: 'Sports',
    tool: 'Gemini',
    useCase: 'Reels profile photo',
    prompt:
      'Prompt Seen style Gemini photo editing prompt: create a cinematic AI portrait of me standing under stadium floodlights, wearing a stylish cricket jersey, dramatic rim light, shallow depth of field, rain particles, confident expression, ultra-realistic 4K Instagram DP edit.',
    image: '/assets/prompt-scenes/cricket-stadium-india-pakistan.png',
    imageAlt: 'Indian and Pakistani cricket creator portrait concept under stadium floodlights for Instagram Reels',
  },
  {
    title: 'Eid Moonlight Couple Edit',
    market: 'Arabic / Bangladesh',
    tag: 'Festival',
    tool: 'ChatGPT',
    useCase: 'Couple photo',
    prompt:
      'Transform this couple photo into an elegant Eid moonlight portrait, warm lanterns, modest festive outfits, glowing crescent moon in the background, cinematic bokeh, soft gold highlights, realistic skin texture.',
    image: '/assets/prompt-scenes/eid-couple-bangladesh-arabic.png',
    imageAlt: 'Bangladesh and Arabic Eid couple moonlight portrait prompt with lanterns for Instagram posts',
  },
  {
    title: 'Bollywood Retro Rain Poster',
    market: 'India / Nepal',
    tag: 'Cinematic',
    tool: 'Gemini',
    useCase: 'Poster edit',
    prompt:
      'Prompt Seen style Gemini prompt: turn my photo into a Bollywood-style rainy retro movie poster, neon street reflections, expressive pose, dramatic teal and amber lighting, 90s film grain, poster composition, high-fashion Instagram look.',
    image: '/assets/prompt-scenes/bollywood-rain-india-nepal.png',
    imageAlt: 'India and Nepal Bollywood rain movie poster AI prompt scene for cinematic Instagram edits',
  },
  {
    title: 'Ramadan Street Portrait',
    market: 'Arabic',
    tag: 'Ramadan',
    tool: 'Any AI image tool',
    useCase: 'Night portrait',
    prompt:
      'Create a respectful Ramadan night street portrait with glowing market lights, elegant traditional styling, soft cinematic shadows, realistic face preservation, warm lantern background, premium Instagram profile photo.',
    image: '/assets/prompt-scenes/ramadan-street-arabic.png',
    imageAlt: 'Arabic Ramadan night street portrait concept with warm market lights for profile photos',
  },
  {
    title: 'South Asian Graduation DP',
    market: 'India / Sri Lanka',
    tag: 'Profile',
    tool: 'ChatGPT',
    useCase: 'Display picture',
    prompt:
      'Generate a clean premium graduation display picture from my photo, modern campus background, confident smile, soft daylight, professional cinematic color grade, crisp details, realistic identity preservation.',
    image: '/assets/prompt-scenes/graduation-south-asia.png',
    imageAlt: 'India and Sri Lanka graduation display picture AI prompt scene with campus daylight',
  },
  {
    title: 'Dark Pinterest Boys Fit Check',
    market: 'South Asia',
    tag: 'Boys',
    tool: 'Gemini',
    useCase: 'Shorts cover',
    prompt:
      'Create a dark Pinterest fit-check edit for a young South Asian creator: black streetwear, clean urban corridor, cinematic smoke, cool cyan edge lighting, sharp realistic face preservation, editorial 4:5 Instagram composition, premium magazine mood.',
    image: '/assets/prompt-scenes/viral-attitude-south-asia.png',
    imageAlt: 'South Asian viral attitude boys neon street edit concept for Instagram Reels cover',
  },
  {
    title: 'Dreamina Arabic Luxury Portrait',
    market: 'Gulf / Arabic',
    tag: 'Luxury',
    tool: 'Dreamina',
    useCase: 'Profile photo',
    prompt:
      'Create a luxury editorial profile portrait with warm desert sunset tones, premium fabric texture, soft cinematic highlights, clean background separation, realistic face details, confident creator look.',
    image: '/assets/prompt-scenes/arabic-luxury-profile.png',
    imageAlt: 'Gulf Arabic luxury editorial profile portrait prompt with desert sunset tones',
  },
  {
    title: 'Festival Family Photo Upgrade',
    market: 'South Asia',
    tag: 'Family',
    tool: 'Any AI image tool',
    useCase: 'Festival post',
    prompt:
      'Enhance this family photo into a polished festival celebration portrait, warm lights, tasteful traditional outfits, natural smiles, realistic skin, balanced composition, social media-ready color grade.',
    image: '/assets/prompt-scenes/festival-family-south-asia.png',
    imageAlt: 'South Asian festival family portrait upgrade prompt with warm lights for Instagram posts',
  },
  {
    title: 'Gemini Clean Studio Portrait',
    market: 'Global',
    tag: 'Gemini',
    tool: 'Gemini',
    useCase: 'Profile photo',
    prompt: 'Use Gemini to create a clean studio portrait from my photo, preserve my facial identity, natural skin texture, crisp eyes, soft neutral background, flattering key light, confident creator expression, 1:1 profile crop, no cartoon effect.',
    image: '/assets/prompt-scenes/graduation-south-asia.png',
    imageAlt: 'Clean Gemini studio profile portrait prompt concept for creators',
  },
  {
    title: 'Gemini Golden Hour Creator Edit',
    market: 'Global',
    tag: 'Gemini',
    tool: 'Gemini',
    useCase: 'Instagram feed',
    prompt: 'Transform my photo in Gemini into a warm golden-hour creator portrait, preserved identity, soft backlight, natural skin tones, stylish casual outfit, shallow depth of field, premium 4:5 Instagram composition.',
    image: '/assets/prompt-scenes/festival-family-south-asia.png',
    imageAlt: 'Golden hour Gemini creator portrait prompt for Instagram feed',
  },
  {
    title: 'ChatGPT Founder Headshot',
    market: 'Global',
    tag: 'ChatGPT',
    tool: 'ChatGPT',
    useCase: 'Personal brand',
    prompt: 'Create a polished founder headshot from this image, modern studio or office background, realistic face preservation, natural skin texture, confident friendly expression, clean lighting, subtle negative space for a launch headline.',
    image: '/assets/prompt-scenes/arabic-luxury-profile.png',
    imageAlt: 'ChatGPT founder headshot prompt with professional studio background',
  },
  {
    title: 'ChatGPT Casual Street Portrait',
    market: 'Global',
    tag: 'ChatGPT',
    tool: 'ChatGPT',
    useCase: 'Creator post',
    prompt: 'Turn this photo into a realistic casual street portrait, preserve my face and expression, soft city background blur, stylish everyday outfit, natural skin, cinematic but not over-edited lighting, 4:5 Instagram crop.',
    image: '/assets/prompt-scenes/viral-attitude-south-asia.png',
    imageAlt: 'ChatGPT casual street creator portrait prompt for Instagram posts',
  },
  {
    title: 'Instagram Reels Hook Cover',
    market: 'Global',
    tag: 'Instagram',
    tool: 'Gemini',
    useCase: 'Reels cover',
    prompt: 'Create a high-contrast Instagram Reels cover from my portrait, preserved face, bold color background, sharp eyes, clean text-safe area at the top, energetic creator mood, 9:16 vertical format, no text added.',
    image: '/assets/prompt-scenes/bollywood-rain-india-nepal.png',
    imageAlt: 'Instagram Reels cover prompt with bold color background and text safe area',
  },
  {
    title: 'Instagram Carousel First Slide',
    market: 'Global',
    tag: 'Instagram',
    tool: 'ChatGPT',
    useCase: 'Carousel cover',
    prompt: 'Design a premium Instagram carousel first-slide portrait from this photo, realistic identity preservation, editorial lighting, clean negative space on the right, 1:1 square composition, magazine-like creator branding, no fake text.',
    image: '/assets/prompt-scenes/cricket-stadium-india-pakistan.png',
    imageAlt: 'Instagram carousel cover prompt with editorial portrait and negative space',
  },
  {
    title: 'Trending Neon Rain Edit',
    market: 'Global',
    tag: 'Trending',
    tool: 'Gemini',
    useCase: 'Viral edit',
    prompt: 'Transform this image into a trending neon rain portrait, wet street reflections, cinematic teal and amber lighting, preserved facial identity, stylish outfit, film grain, dramatic but realistic mood, 4:5 vertical crop.',
    image: '/assets/prompt-scenes/bollywood-rain-india-nepal.png',
    imageAlt: 'Trending neon rain AI photo prompt for viral creator edits',
  },
  {
    title: 'Trending Soft Film DP',
    market: 'Global',
    tag: 'Trending',
    tool: 'ChatGPT',
    useCase: 'Profile refresh',
    prompt: 'Upgrade my portrait into a trending soft-film display picture, gentle window light, realistic skin texture, preserved eyes and face shape, muted warm color grade, clean 1:1 crop, subtle film grain, natural expression.',
    image: '/assets/prompt-scenes/graduation-south-asia.png',
    imageAlt: 'Trending soft film profile photo prompt with natural window light',
  },
  {
    title: 'Profile Photo Minimal Black Background',
    market: 'Global',
    tag: 'Profile',
    tool: 'ChatGPT',
    useCase: 'DP upgrade',
    prompt: 'Create a minimal black-background profile photo from my portrait, preserve identity, sharp eyes, soft rim light, natural skin texture, professional but approachable expression, clean 1:1 crop, no heavy retouching.',
    image: '/assets/prompt-scenes/arabic-luxury-profile.png',
    imageAlt: 'Minimal black background profile photo prompt for creators',
  },
  {
    title: 'Profile Photo Warm Creator Bio',
    market: 'Global',
    tag: 'Profile',
    tool: 'Gemini',
    useCase: 'Bio image',
    prompt: 'Enhance this portrait into a warm creator bio photo, preserved face, soft daylight, clean blurred background, natural skin, relaxed confidence, modern personal brand style, square profile crop and 4:5 feed crop friendly.',
    image: '/assets/prompt-scenes/festival-family-south-asia.png',
    imageAlt: 'Warm creator bio profile photo prompt for personal branding',
  },
  {
    title: 'Cinematic Rooftop Portrait',
    market: 'Global',
    tag: 'Cinematic',
    tool: 'Gemini',
    useCase: 'Poster edit',
    prompt: 'Create a cinematic rooftop portrait from my photo, dusk skyline background, soft rim light, realistic face preservation, stylish jacket, shallow depth of field, premium film still mood, no fake text or logos.',
    image: '/assets/prompt-scenes/viral-attitude-south-asia.png',
    imageAlt: 'Cinematic rooftop portrait prompt for poster style creator edits',
  },
  {
    title: 'Cinematic Window Light Portrait',
    market: 'Global',
    tag: 'Cinematic',
    tool: 'ChatGPT',
    useCase: 'Editorial portrait',
    prompt: 'Turn this photo into a cinematic window-light portrait, soft shadows, preserved facial identity, natural skin texture, elegant outfit, shallow depth of field, filmic contrast, quiet premium editorial mood.',
    image: '/assets/prompt-scenes/arabic-luxury-profile.png',
    imageAlt: 'Cinematic window light portrait prompt for editorial AI photos',
  },
  {
    title: 'Couple Cafe Date Edit',
    market: 'Global',
    tag: 'Couple',
    tool: 'ChatGPT',
    useCase: 'Couple post',
    prompt: 'Transform this couple photo into a realistic cozy cafe date portrait, preserve both faces, warm ambient lights, natural pose, soft background blur, tasteful outfits, romantic but casual Instagram 4:5 composition.',
    image: '/assets/prompt-scenes/eid-couple-bangladesh-arabic.png',
    imageAlt: 'Couple cafe date AI photo prompt for romantic Instagram posts',
  },
  {
    title: 'Couple Travel Memory Poster',
    market: 'Global',
    tag: 'Couple',
    tool: 'Gemini',
    useCase: 'Travel post',
    prompt: 'Create a realistic couple travel memory poster from this image, preserve both identities, scenic background, warm sunrise color, stylish casual outfits, natural smiles, depth of field, premium 4:5 feed composition.',
    image: '/assets/prompt-scenes/eid-couple-bangladesh-arabic.png',
    imageAlt: 'Couple travel memory prompt for Instagram photo edits',
  },
  {
    title: 'Festival Diya Portrait',
    market: 'South Asia',
    tag: 'Festival',
    tool: 'Gemini',
    useCase: 'Festival greeting',
    prompt: 'Create a realistic festival portrait with warm diya glow, tasteful traditional outfit, preserved facial identity, natural skin, marigold accents, soft golden bokeh, family-safe celebration mood, 4:5 Instagram crop.',
    image: '/assets/prompt-scenes/festival-family-south-asia.png',
    imageAlt: 'Festival diya portrait AI prompt for South Asian creator greetings',
  },
  {
    title: 'Festival Lantern Profile',
    market: 'Arabic / South Asia',
    tag: 'Festival',
    tool: 'ChatGPT',
    useCase: 'Profile post',
    prompt: 'Enhance this portrait into a respectful lantern-lit festival profile photo, warm lights, elegant modest outfit, preserved face, natural skin texture, soft bokeh, premium creator DP composition, no exaggerated costume.',
    image: '/assets/prompt-scenes/ramadan-street-arabic.png',
    imageAlt: 'Lantern-lit festival profile prompt for Arabic and South Asian creators',
  },
  {
    title: 'South Asia Campus Creator',
    market: 'South Asia',
    tag: 'South Asia',
    tool: 'Gemini',
    useCase: 'Student profile',
    prompt: 'Generate a South Asian campus creator portrait from this photo, preserved identity, modern college walkway, soft daylight, clean outfit, confident natural smile, realistic skin, 4:5 Instagram and 1:1 DP friendly crop.',
    image: '/assets/prompt-scenes/graduation-south-asia.png',
    imageAlt: 'South Asian campus creator portrait prompt for student profile photos',
  },
  {
    title: 'South Asia Street Market Edit',
    market: 'South Asia',
    tag: 'South Asia',
    tool: 'ChatGPT',
    useCase: 'Lifestyle post',
    prompt: 'Transform this portrait into a South Asian street market creator edit, warm evening lights, tasteful local atmosphere, preserved face, stylish casual or traditional outfit, natural skin, cinematic depth, no brand logos.',
    image: '/assets/prompt-scenes/viral-attitude-south-asia.png',
    imageAlt: 'South Asian street market creator photo prompt for lifestyle posts',
  },
  {
    title: 'Arabic Luxury Studio DP',
    market: 'Arabic',
    tag: 'Arabic',
    tool: 'Dreamina',
    useCase: 'Luxury profile',
    prompt: 'Create a refined Arabic luxury studio profile portrait, preserved identity, warm desert-inspired color palette, premium fabric texture, soft cinematic highlights, modest elegant styling, clean background, realistic skin.',
    image: '/assets/prompt-scenes/arabic-luxury-profile.png',
    imageAlt: 'Arabic luxury studio profile prompt with warm desert-inspired colors',
  },
  {
    title: 'Arabic Night Market Portrait',
    market: 'Arabic',
    tag: 'Arabic',
    tool: 'Gemini',
    useCase: 'Night portrait',
    prompt: 'Transform this portrait into a tasteful Arabic night market photo, warm lantern glow, elegant outfit, preserved face, realistic skin texture, soft background bokeh, premium Instagram 4:5 crop, no religious claims.',
    image: '/assets/prompt-scenes/ramadan-street-arabic.png',
    imageAlt: 'Arabic night market AI photo prompt with warm lantern glow',
  },
  {
    title: 'Dreamina Premium Portrait Pack',
    market: 'Global',
    tag: 'Dreamina',
    tool: 'Dreamina',
    useCase: 'Creator portrait',
    prompt: 'Create a premium Dreamina-style creator portrait, preserved face, high-end fabric detail, soft cinematic highlights, clean background separation, confident expression, realistic skin, editorial 4:5 Instagram composition.',
    image: '/assets/prompt-scenes/arabic-luxury-profile.png',
    imageAlt: 'Dreamina premium creator portrait prompt for editorial AI photo edits',
  },
  {
    title: 'Dreamina Fashion Reel Cover',
    market: 'Global',
    tag: 'Dreamina',
    tool: 'Dreamina',
    useCase: 'Reels cover',
    prompt: 'Generate a Dreamina-style fashion Reels cover from my photo, preserved identity, dramatic studio light, sharp outfit details, bold background, 9:16 vertical composition, clean space for title, premium creator look.',
    image: '/assets/prompt-scenes/viral-attitude-south-asia.png',
    imageAlt: 'Dreamina fashion Reels cover prompt with vertical creator composition',
  }
];

export const categoryGroups: Array<{ title: string; items: Array<[string, string]> }> = [
  {
    title: 'By AI tool',
    items: [
      ['Gemini Prompts', '/gemini-prompts'],
      ['ChatGPT Photo Prompts', '/chatgpt-photo-prompts'],
      ['Dreamina Prompts', '/dreamina-prompts'],
      ['Instagram Prompts', '/instagram-prompts'],
    ],
  },
  {
    title: 'By market',
    items: [
      ['India AI Photo Prompts', '/india-ai-photo-prompts'],
      ['Nepal AI Photo Prompts', '/nepal-ai-photo-prompts'],
      ['Bangladesh AI Photo Prompts', '/bangladesh-ai-photo-prompts'],
      ['Pakistan AI Photo Prompts', '/pakistan-ai-photo-prompts'],
      ['Sri Lanka AI Photo Prompts', '/sri-lanka-ai-photo-prompts'],
      ['Arabic AI Photo Prompts', '/arabic-ai-photo-prompts'],
    ],
  },
  {
    title: 'By creator job',
    items: [
      ['Couple AI Photo Prompts', '/couple-ai-photo-prompts'],
      ['Profile Photo Prompts', '/profile-photo-prompts'],
      ['Cinematic AI Photo Prompts', '/cinematic-ai-photo-prompts'],
      ['Boys AI Photo Prompts', '/boys-ai-photo-prompts'],
      ['Girls AI Photo Prompts', '/girls-ai-photo-prompts'],
      ['Trending Prompts', '/trending-prompts'],
    ],
  },
  {
    title: 'By festival / culture',
    items: [
      ['Cricket AI Photo Prompts', '/cricket-ai-photo-prompts'],
      ['Bollywood AI Photo Prompts', '/bollywood-ai-photo-prompts'],
      ['Diwali AI Photo Prompts', '/diwali-ai-photo-prompts'],
      ['Eid AI Photo Prompts', '/eid-ai-photo-prompts'],
      ['Ramadan AI Photo Prompts', '/ramadan-ai-photo-prompts'],
    ],
  },
];

export const categoryLinks: ReadonlyArray<readonly [string, string]> = categoryGroups.reduce<ReadonlyArray<readonly [string, string]>>(
  (items, group) => [...items, ...group.items],
  [],
);

export const pricing = [
  { name: 'Free', price: '$0', desc: 'Copy prompts for free and claim 1 free image generation after sign-in.', cta: 'Sign in for Free Plan', href: '/app/sign-in?plan=free&next=/generate', items: ['Unlimited prompt browsing', 'Unlimited free prompt copying', '1 free AI photo generation after sign-in', 'Selfie upload for the free generation'] },
  { name: 'Starter', price: '$4.99', desc: 'Starter pack for testing more creator looks.', cta: 'Buy Starter Credits', href: '/app/sign-in?plan=starter&next=/pricing', items: ['60 generation credits', 'About 6 standard AI photo generations', 'Gemini / ChatGPT prompt styles', 'Standard downloads'] },
  { name: 'Pro', price: '$9.99', desc: 'For creators posting new edits every week.', cta: 'Buy Pro Credits', href: '/app/sign-in?plan=pro&next=/pricing', items: ['160 generation credits', 'About 16 standard AI photo generations', 'HD-ready prompt workflows', 'Priority trend packs'] },
  { name: 'Creator', price: '$19.99', desc: 'For agencies and prompt pages running larger batches.', cta: 'Buy Creator Credits', href: '/app/sign-in?plan=creator&next=/pricing', items: ['420 generation credits', 'About 42 standard AI photo generations', 'Bulk prompt planning', 'Priority support'] },
] as const;

export const faqs = [
  ['What is PromptSeen Online?', 'PromptSeen Online is an independent prompt discovery and AI photo workflow site for creators who want ready-to-copy photo prompts for Instagram, Reels, Shorts, and profile pictures.'],
  ['Is PromptSeen Online free to use?', 'You can browse and copy prompt ideas for free. Personalized image generation uses login and credits.'],
  ['Can I use these prompts in Gemini or ChatGPT?', 'Yes. The prompts are written to be adapted for common AI image workflows, including Gemini and ChatGPT image tools.'],
  ['Do I need to upload a photo?', 'Only if you want a personalized AI photo result. You can still browse and copy prompts without uploading.'],
  ['Are my uploaded photos stored?', 'Uploaded photos should only be processed for the requested generation workflow according to the published privacy policy and production storage settings.'],
  ['Can I use generated images on Instagram?', 'Usually yes for personal creator content, but you are responsible for rights, likeness, platform rules, and local regulations.'],
  ['How do credits work?', 'Credits are used for generation actions, not for browsing or copying prompt ideas.'],
  ['Is PromptSeen Online the official Prompt Seen website?', 'No. PromptSeen Online is an independent prompt resource and does not claim official affiliation with any third-party brand or account.'],
] as const;

export const legalPages = {
  'privacy-policy': {
    title: 'Privacy Policy',
    updated: 'July 31, 2026',
    body: [
      'PromptSeen Online is operated by an independent individual operator. This policy explains how we collect, use, disclose, retain, and protect information when you browse prompts, sign in, upload images for AI generation, buy credits or subscriptions, or contact us for support.',
      'Information you provide may include your email address, display name, Google account profile picture, prompts, uploaded photos or selfies, generation settings, support messages, refund requests, and payment-related references. Do not upload photos you do not have permission to use, private identity documents, sensitive images, or content involving minors unless you have all required rights and consent.',
      'Information collected automatically may include IP address, device and browser information, pages viewed, referring URLs, approximate location derived from network data, security logs, cookie identifiers, product events such as prompt copy or pricing clicks, and records needed to prevent abuse, debug errors, and operate credits.',
      'We use this information to provide the website, authenticate accounts through Google OAuth, process AI photo generation with configured providers, store account and generation records, deliver purchased credits or subscriptions, provide support, detect fraud or abuse, improve product quality, measure analytics after consent, and comply with legal, tax, accounting, chargeback, and platform obligations.',
      'PromptSeen uses Cloudflare Workers for hosting and compute, Cloudflare D1 for account and generation records, Cloudflare R2 for uploaded or generated assets when enabled, Google OAuth for sign-in, Stripe for live-capable payment processing, and AI providers such as FAL.ai, OpenAI, and Replicate for real AI image generation workflows when ENABLE_REAL_AI is true.',
      'When analytics consent is accepted, we may load Google Analytics 4 (measurement ID G-HJ16WBEHPL) and Microsoft Clarity (project ID x0vmlezgsz). These providers may process page views, interaction events, device data, approximate location, session behavior, heatmaps, and similar analytics information under their own policies. Analytics scripts are not intentionally loaded before consent.',
      'Payment card details are processed by Stripe or the checkout provider and should not be stored in PromptSeen frontend code. We may receive limited payment metadata such as customer ID, checkout session ID, plan, amount, credit balance, subscription state, invoice, refund, or chargeback status for account, support, tax, fraud, and compliance purposes.',
      'Uploaded photos, prompts, and generated outputs may be sent to AI providers solely to perform the requested generation workflow and return results. AI output quality, rights, and suitability vary by provider and input. You remain responsible for the source image, likeness permissions, prompt text, and publication of any generated image.',
      'We retain account, payment reference, support, security, and generation records only as long as needed for the purposes described above, including service operation, dispute handling, fraud prevention, tax/accounting, legal compliance, and backups. Uploaded assets may be retained for delivery, debugging, abuse prevention, or account history unless deleted or otherwise required by law.',
      'Depending on your location, you may request access, correction, deletion, portability, restriction, or objection regarding your personal information, and you may withdraw analytics consent through Cookie settings. We will respond according to applicable law and may need to verify your account email before acting on a request.',
      'PromptSeen is not directed to children under 13. Do not create an account or upload photos involving children unless you are legally allowed to do so and have appropriate parental or guardian consent. If you believe a child has provided personal information, contact us through the contact page so we can review it.',
      'PromptSeen may be accessed internationally and service providers may process information in countries different from yours. We use reasonable technical and organizational safeguards, but no internet service can guarantee perfect security. If a security issue affects users, we will take appropriate steps according to the circumstances and applicable requirements.',
      'For privacy, deletion, or support requests, use the Contact page or the existing contact email shown there. The intended long-term support address is support@promptseen.online once configured. We may update this policy as the product, providers, or legal requirements change.',
    ],
  },
  'terms-of-service': {
    title: 'Terms of Service',
    updated: 'July 31, 2026',
    body: [
      'PromptSeen Online provides prompt discovery, creator workflow guidance, and live-capable AI photo generation and payment features. The service is operated by an independent individual operator and is not affiliated with any third-party Prompt Seen account, social network, AI platform, Google, Stripe, FAL.ai, OpenAI, Replicate, Cloudflare, or Microsoft Clarity.',
      'By using PromptSeen, you agree to use the service lawfully, provide accurate account and payment information, keep your account secure, and follow these terms, the Privacy Policy, Cookie Policy, AI Content Policy, Refund Policy, checkout terms, and applicable third-party provider rules.',
      'You are responsible for prompts, uploads, source photos, likeness permissions, generated outputs, and how you publish or monetize content. Do not upload content you do not own or have permission to use. Do not impersonate others, mislead viewers, violate privacy, infringe intellectual property, or create illegal, harmful, non-consensual, sexual, hateful, violent, deceptive, or exploitative content.',
      'You retain any rights you have in your uploaded content. You grant PromptSeen and its service providers a limited license to host, process, transmit, reproduce, transform, store, and display your content as needed to operate the requested generation workflow, provide support, maintain safety, comply with law, and enforce these terms.',
      'Prompt libraries, page design, copy, branding, software, and site content are owned by or licensed to PromptSeen unless otherwise stated. You may copy prompts for personal creator use, but you may not scrape, clone, resell, bulk republish, bypass technical limits, or present PromptSeen content as your own competing database without permission.',
      'AI results are probabilistic and may contain errors, artifacts, bias, or unexpected changes. PromptSeen does not guarantee viral performance, identity-perfect outputs, copyright-free results, platform approval, search ranking, uninterrupted availability, or that any generated content is suitable for commercial use.',
      'Paid credits, subscriptions, and plan features are shown at checkout and may depend on provider cost, account status, abuse controls, and product availability. Stripe or another payment provider may process payments. Taxes, currency conversion, bank fees, and payment-provider rules may apply. Credits may be used for generation actions and are not a guarantee of a specific output quality.',
      'If you believe content on PromptSeen infringes your copyright or other rights, contact us through the Contact page with enough detail to identify the work, the allegedly infringing URL or material, your contact information, a good-faith statement, and a statement that your notice is accurate. We may remove or restrict content and may terminate repeat infringers where appropriate.',
      'We may suspend, limit, or terminate access if we believe an account is used for abuse, fraud, chargebacks, security attacks, unlawful content, provider-policy violations, scraping, excessive automated use, or other behavior that risks the service or other users. We may modify or discontinue features with reasonable care for existing users where practical.',
      'To the maximum extent permitted by law, PromptSeen is provided “as is” and “as available.” We disclaim implied warranties of merchantability, fitness for a particular purpose, non-infringement, accuracy, and uninterrupted operation. Our liability is limited to the amount you paid to PromptSeen for the affected service in the three months before the claim, or the minimum amount required by applicable law.',
      'Governing law and venue are to be confirmed for the final operating entity. Until then, these terms should be interpreted as neutral service terms and do not waive mandatory consumer protections that may apply in your location. If any part is unenforceable, the rest remains in effect.',
      'For support, legal notices, privacy requests, or account questions, use the Contact page or the existing contact email shown there. The intended long-term support address is support@promptseen.online once configured.',
    ],
  },
} as const;

export const extraLegalPages = {
  'cookie-policy': {
    title: 'Cookie Policy',
    updated: 'July 31, 2026',
    body: [
      'PromptSeen uses cookies, local storage, and similar technologies to run essential product features, remember account state, protect sessions, prevent abuse, measure performance, and understand product usage when you consent to analytics.',
      'Essential cookies are required for core functionality and security. These may include promptseen_session for OAuth session authentication, signed session protection, account access, abuse prevention, and request integrity. Essential cookies cannot be disabled through the site banner because the service cannot run correctly without them.',
      'Functional local storage may include promptseen_signed_in for frontend sign-in state, promptseen_free_generation_used for free-generation gating, and promptseen_cookie_consent for your cookie choice. These are used to remember product state and your preference on this device.',
      'Analytics cookies and scripts are optional. If you accept analytics, PromptSeen may load Google Analytics 4 (G-HJ16WBEHPL), which can set cookies such as _ga, _gid, and _gat, and Microsoft Clarity (x0vmlezgsz), which can set or use identifiers such as _clck, _clsk, CLID, and MUID for pageview, behavior, heatmap, and session-quality measurement.',
      'GA4 and Clarity are not intentionally loaded until you choose “Accept analytics” in the banner. If you choose “Reject analytics,” PromptSeen stores that choice and continues to load only essential and functional storage needed for the website.',
      'You can change your choice later by using the Cookie settings button. Browser controls can also delete or block cookies, but blocking essential cookies may break sign-in, generation, checkout, or account features.',
      'Typical retention depends on browser settings and provider rules. Session cookies may expire when sessions expire or on logout. Functional local storage remains until you clear it or change your choice. Analytics cookies are retained according to Google and Microsoft settings and policies.',
    ],
  },
  'refund-policy': {
    title: 'Refund Policy',
    updated: 'July 31, 2026',
    body: [
      'This Refund Policy applies to live-capable paid credits, subscriptions, and creator plans purchased through PromptSeen checkout. It does not replace mandatory consumer rights that may apply in your location or the payment provider rules shown at checkout.',
      'Because AI generation uses real provider costs and compute, consumed credits, completed generation jobs, downloaded outputs, and abuse/fraud-related purchases may be non-refundable. If a technical failure prevents delivery and the issue is confirmed in our logs, we may restore credits, retry generation, or refund the affected amount at our discretion.',
      'For first-time purchases, you may request a refund within 7 days if credits have not been substantially used and the request is not connected to abuse, fraud, chargeback manipulation, or violation of the Terms or AI Content Policy. Subscription renewals should be cancelled before the next billing date; refunds for renewals depend on usage, timing, and provider rules.',
      'To request a refund, contact us through the Contact page or existing support email with your account email, payment reference, plan, date, issue description, and any screenshots that help identify the failed transaction or generation job.',
      'Approved refunds are generally returned to the original payment method through Stripe or the relevant payment provider. Processing time depends on the provider, card network, bank, and country. We may ask for identity or account verification before processing support or refund requests.',
      'We may refuse refunds for policy violations, attempts to generate prohibited content, excessive use followed by refund requests, account sharing, scraping, fraudulent payments, chargeback abuse, or requests where the service was delivered as described.',
    ],
  },
  'ai-content-policy': {
    title: 'AI Content Policy',
    updated: 'July 31, 2026',
    body: [
      'PromptSeen supports creator-friendly AI photo workflows. You must use AI generation responsibly and comply with applicable law, third-party AI provider rules, platform rules, and the rights and privacy of people shown in source images or outputs.',
      'You may not use PromptSeen to create or request sexual content, exploitation, child sexual content, hateful or harassing content, graphic violence, self-harm instructions, illegal activity, fraud, doxxing, non-consensual intimate imagery, deepfake deception, political manipulation, or content designed to impersonate, defame, or mislead others.',
      'Only upload photos you own or have permission to use. For private individuals, couples, families, weddings, children, or sensitive cultural and religious contexts, make sure you have consent and avoid outputs that could embarrass, endanger, or misrepresent the people involved.',
      'Do not claim AI-generated images depict real events if they do not. Label or contextualize AI-edited images when the audience could reasonably be misled, especially for ads, sponsored content, public figures, sensitive news, identity documents, medical, legal, financial, or political contexts.',
      'AI systems may produce errors, artifacts, biased results, distorted faces or hands, unsafe text, fake logos, or culturally inappropriate details. You are responsible for reviewing outputs before publishing and for regenerating, editing, deleting, or not using unsafe results.',
      'PromptSeen may block prompts, refuse generation, remove content, suspend accounts, preserve limited evidence, or report activity when needed to enforce this policy, provider rules, payment safety, or legal obligations.',
    ],
  },
  contact: {
    title: 'Contact',
    updated: 'July 31, 2026',
    body: ['For product questions, partnerships, privacy requests, deletion requests, refunds, or support, contact zjjhgtw@gmail.com through the existing support flow. The intended long-term domain support address is support@promptseen.online once configured.', 'We aim to review support and privacy requests within a reasonable timeframe. Include your account email and payment reference when relevant, but do not send passwords, secrets, private keys, or full payment card numbers.'],
  },
} as const;
